
services:
  pico-game:
    build: ./Pico-Game
    container_name: pico-game
    ports:
      - "1089:3000"
    enviroment:
      PUBLIC_IP: "10.56.31.31"
      PUBLIC_PORT: "1089"
    restart: unless-stopped
